# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c9c7b225319deabb2818a4e48f6c697199e2aace97be954e7a83bb7c6409b954dc322bb26f0a1459bc3ee0b1a86092da2d7a3740c758db67aa057f414602c4

test:
  secret_key_base: feff3130241d7d2828b4f5d3ef34feb1eb7b57137a1de69145fff54332d5beb359799c1760f641a6406a71cad1715a0647eb47d64755d6678c005ac5bdcf9b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
