Theme.create(name:"Digital Currency")
Category.create(name:"Wallet", description:"Places to store your digital currency.")
Product.create(name:"Coinbase", category_id:1)
Product.create(name:"Blockchain.info", category_id:1)
Product.create(name:"Copay", category_id:1)
Product.create(name:"Trezor", category_id:1)
Product.create(name:"Opendime", category_id:1)
Product.create(name:"GreenAddress", category_id:1)
Product.create(name:"Mycelium", category_id:1)
Product.create(name:"Multibit", category_id:1)
Product.create(name:"Breadwallet", category_id:1)
